# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='pin',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
