# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20161105_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
