# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20161103_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(auto_now_add=True)),
                ('on_premise', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='child',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='child',
            name='on_premise',
        ),
        migrations.AddField(
            model_name='time',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Child'),
        ),
    ]
